server:
  port: 8084
  ssl:
    enabled: false

spring:
  application:
    name: web
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 300
      max-idle: 100
      max-wait: 1000
    database: 4
    timeout: 100000
  datasource:
    url: jdbc:mysql://localhost:3306/blog_new?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: anywhere
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 300
  freemarker:
    cache: false
    suffix: .ftl
    template-loader-path: classpath:/webapp/templates
    variables:
      title: FishMemory
      canSignup: false
      supportBlack: true
      supportSignUp: false
      domain: blog-dev.yingchengpeng.win
  resources:
    static-locations: classpath:/webapp/static


mybatis:
  typeAliasesPackage: com.ychp.blog.user.model
  mapperLocations: classpath:mapper/*Mapper.xml

logging:
  file: /Users/yingchengpeng/Documents/log/blog/web/root.log

email:
  host: smtp.qq.com
  userName: ychp@yingchengpeng.com
  password: yvdtkyuuratwbdge

mail:
  smtp:
  useSSL: true
  port: 587
  address: ychp@yingchengpeng.com
  user: ychp@yingchengpeng.com
  password: yvdtkyuuratwbdge
  receiver:
  isUsed: true

api:
  ip:
    address:
      type: 1
      apiKey:
