server:
  port: 520
  ssl:
    enabled: false

spring:
  application:
    name: web
  redis:
    host: 127.0.0.1
    port: 6379
    password: anywhere
    pool:
      max-active: 300
      max-idle: 100
      max-wait: 1000
    database: 4
    timeout: 100000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: anywhere
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 300


mybatis:
  type-aliases-package: com.ychp.blog.user.model
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  file: /var/log/blog/root.log



