server:
  port: 8099
  ssl:
    enabled: false

spring:
  application:
    name: web
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_AUTH:anywhere}
    pool:
      max-active: 300
      max-idle: 100
      max-wait: 1000
    database: 4
    timeout: 100000
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:blog-api}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_NAME:root}
    password: ${MYSQL_PASSWORD:anywhere}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 300

mybatis:
  type-aliases-package: com.ychp.user.model, com.ychp.blog.model
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  file: /var/log/blog/root.log

